### ISSUE TITLE
Think about adding tests

### ISSUE THREAD

**Issue by audiodude** [noisebridge/MediaBridge#15]
(self explanatory)

**Comment by jhanley634** [comment]
I feel the best thing you can do is arrange for `$ make test` to run `pytest --cov --cov-report=term-missing`. (It's also possible to run `coverage erase` and friends, but that's a bit more involved.)

If a feature-branch author sees they added a bunch of code which is called as being "not covered", then they _might_ be sufficiently embarrassed that they author the corresponding test. Or not, whatever. But hope springs eternal.

**Comment by audiodude** [comment]
Possbily, but first we have to have tests at all! This issue is to track that.

**Comment by audiodude** [comment]
@cocomittens 

Let's do the structure we talked about (`foo.py`, `foo_test.py`, `foo_testdata.py`). It's fine to have a PR with just one simple test in it. Please document in the README how to run the tests (probably `pipenv run pytest`).

**Comment by audiodude** [comment]
Tests have been added and CI turned on.
