### ISSUE TITLE
Match movies in the Netflix data set to movies on Wikidata

### ISSUE THREAD

**Issue by audiodude** [noisebridge/MediaBridge#2]
[Netflix Data Set (2007)](https://academictorrents.com/details/9b13183dc4d60676b773c9e2cd6de5e5542cee9a)

The only relevant information in the data set is the movie title and year. We would need to search Wikidata using their [REST API](https://www.wikidata.org/wiki/Wikidata:REST_API). We would then want to store the QID (the wikidata ID) of the item along with any relevant "features" (genre, awards, director etc), and map it to the netflix movie id in the dataset. For example.

Netflix Movie Id: 4521
Wikidata ID: Q781324
Title: The Matrix
Year: 1999

**Comment by audiodude** [comment]
Here is a SPARQL query for finding movies from a certain year with a certain title:

```
SELECT * WHERE {
  SERVICE wikibase:mwapi {
    bd:serviceParam wikibase:api "EntitySearch" ;
                    wikibase:endpoint "www.wikidata.org" ;
                    mwapi:search "One Last Dance" ;
                    wikibase:limit 1 ;
                    mwapi:language "en" .
    ?item wikibase:apiOutputItem mwapi:item .
  }
  {
    ?item wdt:P31/wdt:P279* wd:Q11424 ;
          wdt:P577 ?releaseDate ;
          rdfs:label ?itemLabel .
    FILTER("2003-01-01"^^xsd:dateTime <= ?releaseDate && ?releaseDate < "2004-01-01"^^xsd:dateTime) .
    FILTER (lang(?itemLabel) = "en") .
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . } 
  }
}
LIMIT 1
```

This query is for "One Last Dance" and the year 2003, those parameters should be modified.

It can be used to look up movie titles/years in Wikidata, based on the movie name and year. However, we would likely want to expand this with clauses for the other information we want like "genre" (which we can see is P136 on this page: https://www.wikidata.org/wiki/Q1755591). So we would add:

```
...
    ?item wdt:P31 wd:Q11424 ;
          wdt:P577 ?releaseDate ;
          wdt:P136 ?genre .
...
```

However, the genre could be missing, so we should enclose it in an `OPTIONAL` block:

```
...
    ?item wdt:P31 wd:Q11424 ;
          wdt:P577 ?releaseDate .
   OPTIONAL { ?item wdt:P136 ?genre . }
...
```

This query can be used with the Wikidata Query Service REST API, as demonstrated in this Python lesson from the class: https://github.com/noisebridge/PythonClass/blob/main/lessons/10-web-scraping/web-scraping.ipynb

**Comment by audiodude** [comment]
[Wikidata Query Service](https://query.wikidata.org/)

**Comment by audiodude** [comment]
Code from notebook:

```
import requests

query = '''
SELECT DISTINCT ?item ?itemLabel ?rtid WHERE {
  ?item wdt:P136 wd:Q471839.
  ?item wdt:P577 ?pubdate.
  ?item wdt:P1258 ?rtid.
  FILTER((?pubdate >= "1990-01-01T00:00:00Z"^^xsd:dateTime) && ((?pubdate < "2000-01-01T00:00:00Z"^^xsd:dateTime)))
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
'''

resp = requests.post('https://query.wikidata.org/sparql',
              headers={'User-Agent': 'Noisebridge MovieBot 0.0.1/Audiodude <audiodude@gmail.com>'},
              data={
                'query': query,
                'format': 'json',
              }
)
resp.raise_for_status()

data = resp.json()
ids =[d['rtid']['value'] for d in data['results']['bindings']]
```

**Comment by cocomittens** [comment]
Semi functional pr: https://github.com/noisebridge/UntitledPythonProject/pull/8

**Comment by audiodude** [comment]
I will work on the SPARQL query to make it more accurate.

**Comment by audiodude** [comment]
Okay this query gets `Lilo & Stitch` the movie.

```
SELECT * WHERE {
  SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:endpoint "www.wikidata.org";
                      wikibase:api "EntitySearch";
                      mwapi:search "Lilo and Stitch";
                      mwapi:language "en".
      ?item wikibase:apiOutputItem mwapi:item.
  }
  ?item wdt:P31/wdt:P279* wd:Q11424 ;
          wdt:P577 ?releaseDate .
  SERVICE wikibase:label {
    ?item rdfs:label ?temLabel .
    bd:serviceParam wikibase:language "en". 
  }
  FILTER("2002-01-01"^^xsd:dateTime <= ?releaseDate && ?releaseDate < "2003-01-01"^^xsd:dateTime) .
} LIMIT 10
```

The key is removing/extending the limits from both the API request and the query itself. It is possible you will now get multiple hits for the same query, and I'm not entirely sure what we should do in that case. Any ideas?

Also note that the strategy of "search 2 years before and 2 years after" wouldn't work here, because if you do that, you're going to get the spin off movies that came out in 2003.

**Comment by audiodude** [comment]
Also, if you add in the genre, without `LIMIT 1`, you get all the genres:

https://w.wiki/Az$A

**Comment by cocomittens** [comment]
Get either US release date if it exists, or unspecified if not

{
            # Get US release date
            ?item p:P577 ?releaseDateStatement .
            ?releaseDateStatement ps:P577 ?releaseDate .
            ?releaseDateStatement pq:P291 wd:Q30 .  
        }
        UNION
        {
            # Get unspecified release date
            ?item p:P577 ?releaseDateStatement .
            ?releaseDateStatement ps:P577 ?releaseDate .
            FILTER NOT EXISTS { ?releaseDateStatement pq:P291 ?country }
        }
