### ISSUE TITLE
Consider using typer

### ISSUE THREAD

**Issue by audiodude** [noisebridge/MediaBridge#30]
> Clearly the `test` assignment works. But the fact we felt a (helpful!) comment was needed suggests that maybe we're working too hard. Be lazy! Let [typer](https://pypi.org/project/typer) sweat the details about cracking argv. Add a `prod: bool` parameter to the `process_data()` signature. Then you will get `--help` "for free". And no, you certainly don't need to do that in _this_ PR, you might defer that to a subsequent PR.

_Originally posted by @jhanley634 in https://github.com/noisebridge/MediaBridge/issues/17#issuecomment-2438606052_

**Comment by skyfenton** [comment]
Def support this for tools in the future. Is it too early to consolidate the entry points to these scripts in one command line tool with common constants, etc.? Maybe more of a documentation issue, but I still don't know what some files are for yet.

**Comment by audiodude** [comment]
The current file structure is based on guesses before we had any code. Most of it is obsolete and misplaced, but we can tackle that once we have more code and a better idea of what we're building.
