### ISSUE TITLE
Add checks to ensure required files/directories exist

### ISSUE THREAD

**Issue by skyfenton** [noisebridge/MediaBridge#36]
Add checks to create directories and files, and/or warn the user they don't have the required files (ex. netflix dataset downloaded, eventually recommendation model checkpoint file, etc.). Currently, we just run the program until it fails (ex. whole processing script runs and then no "/out" directory exists). I'm sure this is a obvious issue, but I thought I'd document it so we don't forget + can discuss file structure. 

I think this could be added to #28, but we might want to have an extendable way to check for files we require isolated to a designated file.

**Comment by audiodude** [comment]
Yes, we should create the required directories here: https://github.com/noisebridge/MediaBridge/blob/main/mediabridge/data_processing/wiki_to_netflix.py#L14-L15

`os.makedirs(data_dir, exist_ok=True)`, same thing for `out_dir`.

**Comment by audiodude** [comment]
As far as not having the Netflix data, we could definitely add some code that downloads it and decompresses it to the right location. Or we can just wrap the part that tries to read the movie titles in a `try...except` and print a more useful message ("It seems you don't have the Netflix dataset download, please get it from https://....").
